<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>CS3021</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Cascode.Language.Tests" />
    <InternalsVisibleTo Include="Cascode.Cli" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" Version="4.13.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../bench/Cascode.Bench.csproj" />
    <ProjectReference Include="../parser/Cascode.Parser.csproj" />
  </ItemGroup>
</Project>
