<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Cascode.ACIR.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../bench/Cascode.Bench.csproj" />
    <ProjectReference Include="../parser/Cascode.Parser.csproj" />
  </ItemGroup>
</Project>
