<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NativeLib>Shared</NativeLib>
    <PublishAot>true</PublishAot>
    <DisableImplicitLibraryPacksFolder>true</DisableImplicitLibraryPacksFolder>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../language/Cascode.Language.csproj" />
    <ProjectReference Include="../../render/Cascode.Render.csproj" />
  </ItemGroup>
</Project>
