vars: {
  d2-config: {
    layout-engine: tala
  }
}

direction: right

acir_hl: "ACIR-HL\n(slots)"
acir_ml: "ACIR-ML\n(motifs)"
acir_el: "ACIR-EL\n(devices)"
acir_ll: "ACIR-LL\n(geometry)" {
  style.stroke-width: 5
}
gds: "GDS/OASIS"

acir_hl -> acir_ml -> acir_el -> acir_ll -> gds
gds -> drc: "DRC"
gds -> lvs: "LVS"
gds -> pex: "PEX/Sim"
