vars: {
  d2-config: {
    layout-engine: tala
  }
}

direction: right

acir: "ACIR-LL" {style.fill: "#cfd2dd"}
expander: "Expander"
gds: "GDS" {style.fill: "#cfd2dd"}
drc: "DRC tool"
results: "Results" {style.fill: "#cfd2dd"}

acir -> expander -> gds -> drc -> results
