<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\parser\Cascode.Parser.csproj" />
    <ProjectReference Include="..\acir\Cascode.ACIR.csproj" />
  </ItemGroup>
</Project>
