<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Cascode.Render.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../language/Cascode.Language.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.OrTools" Version="9.10.4067" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="symbols\*.svg" />
  </ItemGroup>
</Project>
